### ISSUE TITLE
看起来还可以

### ISSUE THREAD

**Issue by sunnyday2006** [ShenHongFei/utorrent-block-xunlei#1]
啥也不说，先给你个star！

**Comment by ippdesu** [comment]
之前想用C++做来着..webUI这个就免得去程序里面读数据了，准备写一版py的

**Comment by ippdesu** [comment]
唔，发现绿色版的webUI是残的.有点难办了

**Comment by ShenHongFei** [comment]
@ippdesu 我这边用的是  uTorrentPro 3.5.4 (build 44846) [32-bit] ，这能通用吗，不同版本都不一样吧。还有后端的接口也不一定一样。
[https://drive.google.com/open?id=1QAq1yZRsgperen4PBVJSUTXfHXgPN2gH](https://drive.google.com/open?id=1QAq1yZRsgperen4PBVJSUTXfHXgPN2gH)

**Comment by Wickyan** [comment]
https://forum.utorrent.com/topic/49588-%C2%B5torrent-webui/
这里有各个版本的webui 但是我的2.0.4绿色版 webgui好像 还是用不了

**Comment by ShenHongFei** [comment]
有空我试下能不能支持 2.0.4，现在是不支持的

wickyan <notifications@github.com> 于 2020年5月6日周三 下午6:23写道：

**Comment by ShenHongFei** [comment]
@sunnyday2006 @ippdesu 
utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)

@Wickyan 2.0 版本没有 WebUI, 对应的拉取 peers 的接口用不了，没法实现
