### ISSUE TITLE
给各位总结一下我瞎折腾时遇到的问题

### ISSUE THREAD

**Issue by samlee111** [ShenHongFei/utorrent-block-xunlei#12]
简单说是对自己蜜汁自信，粗心大意修改代码导致的各种问题。基本上按主页的说明来操作是不会有任何问题的。

1.运行.bat不需要管理员权限，不管你有没有开UAC，直接运行都能生效。所以不存在编辑这个文件改路径的问题。
2.所以也不需要单独再安装nodejs，压缩包里有了，也不用系统路径里添加nodejs。
3.utorrent.js文件编辑的时候，双击选中字段的话会把引号和**逗号**也选中，补了引号不要忘记补逗号。
4.本人Win10系统，复制uTorrent根目录路径下来是“\”，虽然不清楚路径里“\”和“/”不同是否有影响，但如果要改过来的话，**不要用全文替换**，文件中本身有很多“\”。

PS.运行成功后可以最小化，每30秒会做一次屏蔽匹配。

**Comment by ShenHongFei** [comment]
@samlee111 utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
