### ISSUE TITLE
请问一下UT3.55的远程控制端口在哪里找？

### ISSUE THREAD

**Issue by JackieMa-1981** [ShenHongFei/utorrent-block-xunlei#13]
远程控制页面变成了remote.utorrent.com加上自定义的账号密码，不知道要如何查看本地的管理端口了，求帮助，谢谢。

**Comment by ShenHongFei** [comment]
@JackieMa-1981 "uTorrent 设置 > 连接 > 监听端口 > 传入连接所使用的端口" 中设置的端口号。

utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
