### ISSUE TITLE
xunlei/0.0.1.8无法屏蔽

### ISSUE THREAD

**Issue by mochen91** [ShenHongFei/utorrent-block-xunlei#14]
作者大大还在吗？xunlei/0.0.1.8  这种的还是没有屏蔽 xunlei0012-XXX这种倒是一下子就给屏蔽了。

**Comment by ShenHongFei** [comment]
理论上是可以屏蔽的，你检查下是不是高级选项里没开 ipfilter.dat

**Comment by ShenHongFei** [comment]
@mochen91 utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)

**Comment by tzwken** [comment]
https://github.com/tzwken/utorrent-block
试试这个。
  支持自定义要屏蔽的客户端信息。
  每两小时自动清屏蔽列表
  golang开发，程序体积小运行速度快。
