### ISSUE TITLE
免安装版问题

### ISSUE THREAD

**Issue by ghost** [ShenHongFei/utorrent-block-xunlei#15]
你好。我使用的免安装没有C盘appdate没有ipfilter，然后我自己创建了一个，编辑脚本后依然无法使用，必须要用安装版吗？？

**Comment by ShenHongFei** [comment]
在便携版文件夹（以及子文件夹）里找一找 settings.dat, resume.dat 文件，在旁边新建一个 ipfilter.dat ，然后把路径设置到这里就 OK 了。

**Comment by ShenHongFei** [comment]
> portable 版的 ipfilter 文件要设置在这个位置 uTorrentPortable vXXX_Stable_Plus_Portable/App/uTorrent/ipfilter.dat
> 设置在 C:/Users/xxx/AppData/Roaming/uTorrent/ipfilter.dat 是没用的

https://github.com/ShenHongFei/utorrent-block-xunlei/issues/5#issuecomment-501666287

**Comment by 123336-mike** [comment]
> > portable 版的 ipfilter 文件要设置在这个位置 uTorrentPortable vXXX_Stable_Plus_Portable/App/uTorrent/ipfilter.dat
> > 设置在 C:/Users/xxx/AppData/Roaming/uTorrent/ipfilter.dat 是没用的
> 
> [#5 (comment)](https://github.com/ShenHongFei/utorrent-block-xunlei/issues/5#issuecomment-501666287)

你好，我换了ut2.2.1,设置和webui都好了，ipfilter也创建了
![批注 2020-08-03 151953](https://user-images.githubusercontent.com/60338269/89156292-02190f80-d59d-11ea-9c7d-a71b11f3c254.png)
![批注 2020-08-03 152106](https://user-images.githubusercontent.com/60338269/89156303-080ef080-d59d-11ea-8388-905d7f4b44f3.png)

但感觉依然没成功，是为什么啊

**Comment by SeaHOH** [comment]
```
Mac:
        ~/Library/Application Support/uTorrent
        或
        /Applications/uTorrent.app/Contents/MacOS
Unix utserver:
        使用 utserver 参数 "-settingspath" 指定配置文件夹路径。
Win XP:
        C:\Documents and Settings\<用户名>\Application Data\uTorrent
Win 7 及以上:
        C:\Users\<用户名>\AppData\Roaming\uTorrent
便携模式:
        μTorrent 安装文件夹路径。要启用此模式，先把 settings.dat 文件放入其中。
PortableApps:
        <PortableApps 文件夹>\App\uTorrent
Android:
        我不知道相关的一切信息，欢迎帮助补充此信息，包括 Android 可能是不适用的。
网络文件:
        在其它设备上运行 μTorrent，并配置其配置文件夹为网络路径。
        例如
        SMB/CIFS  //machine1/share/uTorrent
        NFS       mount –t nfs 192.168.1.20:/var/lib/utserver /mnt/utserver
                  /mnt/utserver
```

**Comment by SeaHOH** [comment]
> 我换了 ut2.2.1,

这个版本的 ut 无法使用此脚本

**Comment by 123336-mike** [comment]
> > 我换了 ut2.2.1,
> 
> 这个版本的 ut 无法使用此脚本
哦哦，主要新版有广告。。。。。

**Comment by SeaHOH** [comment]
去广告教程 https://github.com/SeaHOH/ban-peers/issues/1

**Comment by loading1688** [comment]
大佬你好！能不能把更新的打个包！谢谢啊！O(∩_∩)O

**Comment by 123336-mike** [comment]
> 的打个包！谢谢啊！O(∩

要哪个版本的？？

**Comment by 123336-mike** [comment]
http://www.oldversion.com/windows/utorrent-2-2-1-2

**Comment by loading1688** [comment]
> > 的打个包！谢谢啊！O（∩
> 
> 要哪个版本的？？

说的是屏蔽迅雷脚本O(∩_∩)O

**Comment by 123336-mike** [comment]
> > > 的打个包！谢谢啊！O（∩
> > 
> > 
> > 要哪个版本的？？
> 
> 说的是屏蔽迅雷脚本O(∩_∩)O

直接下载就可以了啊

**Comment by loading1688** [comment]
> > > > 的打个包！谢谢啊！O（∩
> > > 
> > > 
> > > 要哪个版本的？？
> > 
> > 
> > 说的是屏蔽迅雷脚本O（∩_∩）O
> 
> 直接下载就可以了啊

你好！下载的是以前的!不是更新后的啊！

**Comment by SeaHOH** [comment]
你可以搜索 npm + TypeScript 获取运行方法，或者可以试试我写的 Python 工具，上方有链接。

**Comment by loading1688** [comment]
> 你可以搜索npm + TypeScript获取运行方法，或者可以试试我写的Python工具，上方有链接。

你那个我试了两天没按上！就是没懂啊！电脑本身安装有Python 3.8 鼓捣半天就是没搞懂！O(∩_∩)O

**Comment by SeaHOH** [comment]
直接 pip 命令安装就行，莫非你安装 Python 时没有安装 pip 工具和启用 PATH？

**Comment by loading1688** [comment]
> 直接pip命令安装就行，莫非你安装Python时没有安装pip工具和启用PATH？
我那个是用Qb搜索才安装的！不会弄那个软件！

**Comment by SeaHOH** [comment]
你用 qB？这里的工具都是针对 uT 的。

**Comment by SeaHOH** [comment]
你可以试试 qBEE，仓库首页有链接。

**Comment by loading1688** [comment]
> 你可以试试qBEE，仓库首页有链接。

QB下载速度太慢了！我天天挂着啊！所以又回到UT了！

**Comment by loading1688** [comment]
![捕获](https://user-images.githubusercontent.com/73093231/96572852-f1587a00-12ff-11eb-8fcf-05c9ee1477dc.JPG)
你看看！O(∩_∩)O

**Comment by 123336-mike** [comment]
> > 你可以试试qBEE，仓库首页有链接。
> 
> QB下载速度太慢了！我天天挂着啊！所以又回到UT了！

那是你不会用，ut,qb都用的篇p2p技术，同一个种子在相同网络相同时间速度是一样的

**Comment by loading1688** [comment]
现在用的以前的！就会用这个大佬的脚本！
![Uploading 捕获.JPG…]()

**Comment by 123336-mike** [comment]
> > 你可以试试qBEE，仓库首页有链接。
> 
> QB下载速度太慢了！我天天挂着啊！所以又回到UT了！

qb添加tracker,更改高级设置，速度还是不错的，除非是死种

**Comment by loading1688** [comment]
https://subhd.tv/u/loading1688
那个是我！你说我不会用吗？

**Comment by 123336-mike** [comment]
> > 你可以试试qBEE，仓库首页有链接。
> 
> QB下载速度太慢了！我天天挂着啊！所以又回到UT了！

开启路由器upnp,去获取公网都可以有效提高速度，内网速度差点，但也有的

**Comment by 123336-mike** [comment]
> > > 你可以试试qBEE，仓库首页有链接。
> > 
> > 
> > QB下载速度太慢了！我天天挂着啊！所以又回到UT了！
> 
> 开启路由器upnp,去获取公网都可以有效提高速度，内网速度差点，但也有的

国内字幕组的种子一般就开头一两个月有速度，后头基本都死了

**Comment by SeaHOH** [comment]
合集还是比较持久的。

**Comment by ShenHongFei** [comment]
@loading1688 utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
