### ISSUE TITLE
影响下载速度

### ISSUE THREAD

**Issue by DamnCrab** [ShenHongFei/utorrent-block-xunlei#16]
运行一小时左右下载速度急剧下降，手动清理ipfilter.dat之后速度提升。
版本3.5.5 能否加入自动清理ipfilter.dat功能

**Comment by ShenHongFei** [comment]
好的，有空加一下，不过为什么会速度会急剧下降呢？

**Comment by SeaHOH** [comment]
自动清理很有必要，但不太可能是影响下载速度的原因，尤其是你这才运行一小时。

**Comment by ShenHongFei** [comment]
utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)

下个 release 版本支持 REPL, 可实时操控 utorrent 状态
或者执行 npx utorrent-block-xunlei
然后在窗口里粘贴以下代码

```ts
async function delay (milliseconds) {
    return new Promise( resolve => {
        setTimeout(resolve, milliseconds)
    })
}

;(async () => {
    while (true) {
        await delay(1000 * 间隔秒数)
        await utorrent.reset_ipfilter()
    }
})()
```
