### ISSUE TITLE
出現錯誤，但我反覆確認過網址、帳號密碼皆正確

### ISSUE THREAD

**Issue by xyz321763** [ShenHongFei/utorrent-block-xunlei#17]
我有按照設定也試過用網頁開，正常可以瀏覽，但按運行就是這個畫面
請問這是哪裡有問題?

![未命名](https://user-images.githubusercontent.com/73183168/96603122-4d35f980-1326-11eb-8641-5a367e7e40e5.png)

**Comment by xyz321763** [comment]
我剛發現了用3.x以上版本就可以正常運行
但是我的版本是2.0.1不能用
請問有辦法改成2.0.1版可以用的嗎? (因為我們這地方擋3.x以上版本)

**Comment by ShenHongFei** [comment]
2.0.1 版本的目前获取不到实时连接的 peers 信息，只有 3.x 版本的，并且打开 webui 才可以，所以改不了

**Comment by xyz321763** [comment]
好的謝謝
