### ISSUE TITLE
你好 请问最新的release整合什么时候发布

### ISSUE THREAD

**Issue by TYu89879997** [ShenHongFei/utorrent-block-xunlei#19]
看了那个代码  实在不会使用  毕竟不是专业的程序员  只会依葫芦画瓢

**Comment by SeaHOH** [comment]
可以使用 [ts-node](https://github.com/TypeStrong/ts-node) 直接运行而无需编译。
如果你有用 python，可在 readme 中查看另一个我写的类似工具的链接。

**Comment by TYu89879997** [comment]
汗  抱歉  怪我没说清楚  其实我也不是程序员  我只是个喜欢用utorrent制作种子上传的闲人  你给我说的这个工具我完全不懂  我现在用的那个V1.0版的屏蔽效果确实非常好  现在感觉就缺这个新的屏蔽策略 因为遇到了用其他BT软件(像Deluge、Transmission)的人不开上传就是只下载的情况  这个新的屏蔽策略代码 我不知道是不是可以直接复制粘贴到utorrent.js里面  如果可以的话 粘贴到任何位置都行吗

**Comment by SeaHOH** [comment]
这个工具主要是针对本身就恶意吸血性质的客户端，没法屏蔽基于配置吸血的正规客户端。
如果你需要屏蔽正规客户端，安装 python 后再安装我那个工具。安装和使用方法在工具页面有详细说明。

另，我那个工具默认不作用于私种，可以使用参数启用，可能会对 PT 帐号有不好的影响，因此建议还是不启用。

**Comment by lucktu** [comment]
我也期待可以使用最新的代码，希望早日release

**Comment by ShenHongFei** [comment]
@TYu89879997 @SeaHOH @lucktu 已发布 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases/](https://github.com/ShenHongFei/utorrent-block-xunlei/releases/)

**Comment by ShenHongFei** [comment]
欢迎试用并反馈
