### ISSUE TITLE
webui can not load peer info

### ISSUE THREAD

**Issue by USERS-ROOT** [ShenHongFei/utorrent-block-xunlei#2]
utorrent version is 2.2.1   webui version is 0.338.    how to load peer info?

**Comment by USERS-ROOT** [comment]
![mmexport1543417497283](https://user-images.githubusercontent.com/35726402/49160716-56003980-f362-11e8-9379-8ac7175598c1.jpg)

**Comment by ShenHongFei** [comment]
Have you got the token and torrent list successfully through the webui?

**Comment by ShenHongFei** [comment]
咦，我刚好在下第三个种子，这么巧。

**Comment by USERS-ROOT** [comment]
用浏览器上的，别的都能看见，唯独peer list显示不出来

**Comment by ShenHongFei** [comment]
我这边用的是 uTorrentPro 3.5.4 (build 44846) [32-bit]
![0017](https://user-images.githubusercontent.com/15074472/49161585-1d615f80-f364-11e8-8a95-84ad95d50b09.png)

**Comment by USERS-ROOT** [comment]
![default](https://user-images.githubusercontent.com/35726402/49196635-9f827000-f3c6-11e8-8183-2732a7d941a4.png)
运行提示param...错误 删掉后边三个点又提示后边的错误

**Comment by ShenHongFei** [comment]
[https://www.npmjs.com/package/coffeescript](https://www.npmjs.com/package/coffeescript)
是这个最新版的 coffeescript 吗？

**Comment by USERS-ROOT** [comment]
我是通过npm install  coffee 安装的

**Comment by ShenHongFei** [comment]
@USERS-ROOT 是 npm install coffeescript 不是 npm install coffee

**Comment by USERS-ROOT** [comment]
![screenshot_2018-11-29-16-37-20-748_com microsoft rdc android](https://user-images.githubusercontent.com/35726402/49209433-70cfbe00-f3f5-11e8-9f32-386ec0550728.png)

能运行了，但还是不能ban掉迅雷呢？

**Comment by ShenHongFei** [comment]
@USERS-ROOT 不好意思，从你的日志里面发现上传的脚本少了一些导入语句，等我修改一下重新上传一份。

**Comment by ShenHongFei** [comment]
@USERS-ROOT 在脚本的第一行插入下面这句
fs = require 'fs'

**Comment by USERS-ROOT** [comment]
@ShenHongFei 好用了 感谢
