### ISSUE TITLE
你好,希望解决人工手动屏蔽无效的问题

### ISSUE THREAD

**Issue by TYu89879997** [ShenHongFei/utorrent-block-xunlei#21]
就是我手动去屏蔽一些吸血不上传的正规客户端，就是复制它的ip地址粘贴到ipfilter.dat后，过了一会这个吸血的正规客户端又出现在我的下载列表里了，能否弄个代码什么的让这些手动屏蔽的吸血正规客户端不再恢复，我觉得把这个问题解决了，这个脚本就又上一层楼了。对了，我现在用的版本仍然是utorrent-block-xunlei-v1.0

**Comment by ShenHongFei** [comment]
utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
