### ISSUE TITLE
请教一个问题，为什么屏蔽7开头的ip

### ISSUE THREAD

**Issue by yukinotech** [ShenHongFei/utorrent-block-xunlei#22]
peer.client.match(/(-XL0012-)|(Xunlei)|(^7\.)|(QQDownload)/i)

**Comment by yukinotech** [comment]
查了一下，貌似是7开头的ip是美国国防部。。

**Comment by ShenHongFei** [comment]
不是根据 IP 屏蔽的，是根据使用的客户端 (Client UA)，7 开头的是迅雷
