### ISSUE TITLE
不知道aria2是否也能通过类似的思路屏蔽迅雷呢？

### ISSUE THREAD

**Issue by Mosney** [ShenHongFei/utorrent-block-xunlei#3]
aria2的BT功能似乎比较简单，也没有API，只有通过RPC与aria2server通信，希望repo主有时间看一下。

> 毕竟使用服务器挂BT的用户也大有人在，相比较而言服务器因为长时间挂机所以被吸血的时间会更久、受迅雷毒害更深一点。

**Comment by ShenHongFei** [comment]
@Mosney 
你的需求有人在 aria2 里提过了，不过没人理。
[https://github.com/aria2/aria2/issues/1294](https://github.com/aria2/aria2/issues/1294)
我记得 aria2 在 BT 下载的时候并不显示 peers ，而且没有屏蔽 IP 的功能，那么只能通过改 aria2 的源代码来屏蔽了吧，但这个不是我力所能及的。
况且，用服务器挂 BT 不止 aria2 这一种选择啊，uTorrent 和 qBittorrent 也都可以在没有图形界面的 linux 上运行然后通过 Web 界面访问。

**Comment by Mosney** [comment]
@ShenHongFei 可以显示peer，我用的AriaNG图形化就可以查看，但是不能进行任何操作。  
服务器装着transmission挂PT，http什么的都用aria2，所以就想偷懒BT也直接用aria2好了，结果发现有被吸血且无能为力的风险。只能等aria2开发者咯，还是谢谢repo主的回复
