### ISSUE TITLE
这个不能实时跳掉客户端?我在ut的用户列表里点重新载入ipfilter才实时生效的样子

### ISSUE THREAD

**Issue by cnrting** [ShenHongFei/utorrent-block-xunlei#5]
看日志显示已经把ip加进ipfilter了，可为什么还在上传额，是不是不能实时踢掉xl客户端啊，看了下效果，ut列表里时刻有一堆xl客户端

**Comment by ShenHongFei** [comment]
正常的话每隔半分钟会踢掉所有的 XL 客户端，没有踢掉的话检查一下高级设置里有没有启用 ipfilter。

**Comment by ShenHongFei** [comment]
或者你也可以在代码里改一下检测的间隔时间，可以把时间改的短一点。

**Comment by foxdodo** [comment]
portable版的ipfilter文件要设置在这个位置 uTorrentPortable vXXX_Stable_Plus_Portable/App/uTorrent/ipfilter.dat  
设置在C:/Users/xxx/AppData/Roaming/uTorrent/ipfilter.dat  是没用的

**Comment by 123336-mike** [comment]
> portable版的ipfilter文件要设置在这个位置 uTorrentPortable vXXX_Stable_Plus_Portable/App/uTorrent/ipfilter.dat
> 设置在C:/Users/xxx/AppData/Roaming/uTorrent/ipfilter.dat 是没用的

好的，我试试，非常感谢

**Comment by ShenHongFei** [comment]
utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
