### ISSUE TITLE
webui浏览器访问正常但是脚本运行Err400

### ISSUE THREAD

**Issue by m0nkeyd** [ShenHongFei/utorrent-block-xunlei#6]
webui版本 v0.388 utorrent2.0.4，webui是加那个webui.zip装上去的，脚本里/gui/没落下，直接用浏览器访问没有问题。但是脚本不管是本机走127.0.0.1还是别的机器走ip都是invalid request。
跪谢

**Comment by m0nkeyd** [comment]
手工写ip进ipfilter.dat也可以生效

**Comment by ShenHongFei** [comment]
是不是 utorrent 版本的问题？2.0.4 这个版本有点旧，我没有测试过。

**Comment by BROBIRD** [comment]
@ShenHongFei 
我这里2.2.1也是 `400 invalid request`

**Comment by yaubio** [comment]
的确是版本的问题，更新到3.5.5正常

**Comment by ZzMark** [comment]
2.0 没有 getpeers 这个 action，没法使用
