### ISSUE TITLE
与uTorrent连接时产生大量Time Wait状态的TCP连接

### ISSUE THREAD

**Issue by hiiragiyuriko** [ShenHongFei/utorrent-block-xunlei#7]
系统：Windows 7 32位
uTorrent版本：3.5.5

在输出“开始运行”的字样后，使用netstat命令可看到大量Time Wait连接，这些连接的目标是我uTorrent的Web管理端口

脚本的屏蔽功能虽能正常运行，但希望开发者可以优化一下这个问题以避免产生过多的资源消耗。

附图一张：
https://blog.hiirachan.moe/usr/uploads/2019/06/2327615273.png

**Comment by ShenHongFei** [comment]
感谢反馈，我研究一下这个问题。

**Comment by tzwken** [comment]
使用golang开发，程序体积小，可满足你的需求。
功能亮点：
    支持自定义要屏蔽的客户端信息。
    程序退出自动清理屏蔽列表或每两小时清理一次清屏蔽列表。

https://github.com/tzwken/utorrent-block
