### ISSUE TITLE
同一個IP一直沒有被block

### ISSUE THREAD

**Issue by tonyhsie** [ShenHongFei/utorrent-block-xunlei#8]
今天遇到一個奇怪的現象

同一個IP，已經被寫到 ipfilter.dat 裡了，也確定 ipfilter 有作用，但就是一直沒被 ut 踢掉

![未命名](https://user-images.githubusercontent.com/52758827/62339994-937c1e80-b510-11e9-833b-a3cd36c15d50.png)
![圖片 2019-08-02 10-22-55](https://user-images.githubusercontent.com/52758827/62339866-1cdf2100-b510-11e9-9110-e2b07464a603.png)
![圖片 2019-08-02 10-23-39](https://user-images.githubusercontent.com/52758827/62339870-2072a800-b510-11e9-95dc-99f76f97b16b.png)

之前沒遇過這樣的現象，重開 uTorrent 及 utorrent-block-xunlei 後，也正常踢掉其它IP了

不曉得大家有沒有遇過類似的情況?

**Comment by ShenHongFei** [comment]
utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
