### ISSUE TITLE
请问下，怎么修改 root_url？

### ISSUE THREAD

**Issue by ohhhyy** [ShenHongFei/utorrent-block-xunlei#9]
脚本里地址是http://127.0.0.1:1000/gui/，UT里面需要怎么设置？
另外ipfilter_path是不是不能出现中文路径？

**Comment by ShenHongFei** [comment]
只需要修改那个端口（冒号后面的数字），你可以设置为 uTorrent 的监听端口（如第二张图），或者在图一种启用备用端口，将端口设置为这边的备用端口。
![2019 08 17 23-51-20](https://user-images.githubusercontent.com/15074472/63214388-399f6980-c14a-11e9-8e70-8a899fa36196.png)
![2019 08 17 23-52-56](https://user-images.githubusercontent.com/15074472/63214389-3a380000-c14a-11e9-95dc-9a654d5713cd.png)

ipfilter_path 可以是中文路径

**Comment by ohhhyy** [comment]
已解决，谢谢
